"""Core package for security, dependencies, responses, and exceptions."""

from app.core.dependencies import (
    get_current_user,
    get_current_user_optional,
    require_permission,
    get_current_active_superuser,
)
from app.core.security import (
    hash_password,
    verify_password,
    create_access_token,
    create_refresh_token,
    verify_token,
    decode_token,
    extract_token_payload,
    create_email_verification_token,
    verify_email_verification_token,
    create_password_reset_token,
    verify_password_reset_token,
)
from app.core.responses import (
    StandardResponse,
    ErrorDetail,
    PaginatedResponse,
    success_response,
    error_response,
    paginated_response,
)
from app.shared.exceptions import (
    AppException,
    AuthenticationError,
    InvalidCredentialsError,
    TokenExpiredError,
    InvalidTokenError,
    UnverifiedEmailError,
    InactiveAccountError,
    PermissionDeniedError,
    InsufficientPermissionsError,
    ValidationError,
    DuplicateEmailError,
    DuplicateResourceError,
    InvalidFileTypeError,
    FileTooLargeError,
    WeakPasswordError,
    NotFoundError,
    UserNotFoundError,
    RoleNotFoundError,
    PermissionNotFoundError,
    PlanNotFoundError,
    RateLimitExceededError,
    EmailServiceError,
    StorageServiceError,
    DatabaseError,
    BadRequestError,
    InternalServerError,
)

__all__ = [
    # Dependencies
    "get_current_user",
    "get_current_user_optional",
    "require_permission",
    "get_current_active_superuser",
    # Security
    "hash_password",
    "verify_password",
    "create_access_token",
    "create_refresh_token",
    "verify_token",
    "decode_token",
    "extract_token_payload",
    "create_email_verification_token",
    "verify_email_verification_token",
    "create_password_reset_token",
    "verify_password_reset_token",
    # Responses
    "StandardResponse",
    "ErrorDetail",
    "PaginatedResponse",
    "success_response",
    "error_response",
    "paginated_response",
    # Exceptions
    "AppException",
    "AuthenticationError",
    "InvalidCredentialsError",
    "TokenExpiredError",
    "InvalidTokenError",
    "UnverifiedEmailError",
    "InactiveAccountError",
    "PermissionDeniedError",
    "InsufficientPermissionsError",
    "ValidationError",
    "DuplicateEmailError",
    "DuplicateResourceError",
    "InvalidFileTypeError",
    "FileTooLargeError",
    "WeakPasswordError",
    "NotFoundError",
    "UserNotFoundError",
    "RoleNotFoundError",
    "PermissionNotFoundError",
    "PlanNotFoundError",
    "RateLimitExceededError",
    "EmailServiceError",
    "StorageServiceError",
    "DatabaseError",
    "BadRequestError",
    "InternalServerError",
]

